### ISSUE TITLE
Return a list of 2 MarkedStrings for function/classes in textDocument/hover

### ISSUE THREAD

**Issue by rwols** [muffinmad/anakin-language-server#11]
The first MarkedString should be of the form

`{"language": "python", "value": "def foo(bar, baz) -> None"}` (put the word `def` in front of it for a function/method, `class` for a class)

The second MarkedString should be the plaintext docs of the function/class.

Right now the hover content is a bit dry, I think this can be improved greatly with this simple adjustment.

![Screenshot from 2020-05-15 20-51-23](https://user-images.githubusercontent.com/2431823/82085813-d8fb8800-96ed-11ea-88c7-be49ccde49bc.png)

**Comment by muffinmad** [comment]
`MarkedString` is deprecated and it is [recommended](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_hover) to use `MarkupContent` instead.

**Comment by rwols** [comment]
True, but MarkedString[] is a bit easier to implement in this case.

You can also return MarkupContent like this perhaps:

````
```python
<def or class> entity
```

```
docstring of entity
```
````
If you don't wrap the docstring in triple backticks you run the risk of not faithfully representing indentation of the docstring.

**Comment by rwols** [comment]
Of course first detecting whether the client supports `markdown` content (which the LSP plugin does).

**Comment by muffinmad** [comment]
Great idea! Though with `class` prefix doesn't look nice:

<img width="852" alt="Screenshot 2020-05-16 at 00 03 47" src="https://user-images.githubusercontent.com/2702727/82096407-98aa0300-9709-11ea-8964-4873533ebc73.png">
