### ISSUE TITLE
textDocument/documentHighlight

### ISSUE THREAD

**Issue by rwols** [muffinmad/anakin-language-server#13]
pyls has textDocument/documentHighlight. I'm not sure how it achieves it, but in any case I'm missing that feature in anakinLS.

**Comment by muffinmad** [comment]
Right after https://github.com/davidhalter/jedi/pull/1590

**Comment by rwols** [comment]
"highlights all references to the symbol in the current file" is not an optimal experience. It should instead highlight all references to the symbol in the *current scope*.

For example if I have two functions:

```python

def f():
    a = 1
    b = 2
    a = b + 3

def g():
    a = 1
    b = 2
    a + b + 3
```

And I put my cursor on the `a` in `f`, then it should highlight the two occurrences of `a` in `f`, but **not in** `g`. And alternatively, if I put my cursor on the `a` in `g`, it should not highlight the occurrences in `f`.

If instead we have this situation:
```python
a = 0

def f():
    global a
    a = 1
    b = 2
    a = b + 3

def g():
    global a
    a = 1
    b = 2
    a + b + 3
```
Then putting the cursor on the `a` in `f` *should* highlight the `a` occurences in `f` *and* `g`.

It should also mark variable assignments as "Write" (from the spec) and non-assignments as "Read" (from the spec).

It's a pretty nice feature if you're dealing with very large functions.

**Comment by muffinmad** [comment]
> "highlights all references to the symbol in the current file" is not an optimal experience. It should instead highlight all references to the symbol in the _current scope_.

Exactly. Take a look at "prerelease" screenshots:

> And I put my cursor on the `a` in `f`, then it should highlight the two occurrences of `a` in `f`, but **not in** `g`.

<img width="294" alt="Screenshot 2020-05-22 at 12 28 44" src="https://user-images.githubusercontent.com/2702727/82653569-16996d00-9c28-11ea-9634-b45bf4ab854a.png">

> Then putting the cursor on the `a` in `f` _should_ highlight the `a` occurences in `f` _and_ `g`.

<img width="294" alt="Screenshot 2020-05-22 at 12 10 56" src="https://user-images.githubusercontent.com/2702727/82653635-303ab480-9c28-11ea-99a7-916ae7f3a2cf.png">
 
> It should also mark variable assignments as "Write" (from the spec) and non-assignments as "Read" (from the spec).

This one is not done yet.

**Comment by rwols** [comment]
Ah cool! I did not check out your pre-release. I'm glad this is going in the right direction :)
