### ISSUE TITLE
[pycodestyle] read tox.ini (or any other relevant config file)

### ISSUE THREAD

**Issue by rwols** [muffinmad/anakin-language-server#3]
I have a tox.ini in my project with the following section:

```
[pycodestyle]
max-line-length = 120
```

However, anakin-language-server seems to ignore this setting. See #1 for an example screenshot where pycodestyle says the line length is too long.

**Comment by muffinmad** [comment]
Oh, I see. While user-level configuration is works fine, e.g. `~/.config/pycodestyle`, project-level configuration is not.

**Comment by rwols** [comment]
You may need to read the workspace folders from the editors’ initialize request to figure out where project config files may live.

**Comment by muffinmad** [comment]
Fixed in https://github.com/muffinmad/anakin-language-server/commit/44f76a27e017743124b2615e02331d5c6452c851
