### ISSUE TITLE
Duplicate code completion items

### ISSUE THREAD

**Issue by rwols** [muffinmad/anakin-language-server#5]
I'm getting a few duplicate code completion items.

![Peek 2020-05-03 23-27](https://user-images.githubusercontent.com/2431823/80926179-d9af2880-8d95-11ea-9c96-87d355310369.gif)

**Comment by muffinmad** [comment]
Consider attach `textDocument/completion` request and server response.

Also can you please share project settings? Didn't touched ST for a while, can't figure out how to get completions for `sublime` module.

Thanks.

**Comment by rwols** [comment]
I don't see this happening anymore on 1.5. I'll re-open if I see it happening again and attach a log.

FWIW You can do the following to test this in ST3:

1. Download ST3
2. Install [LSP plugin](github.com/sublimelsp/LSP)
3. Run `pref:lsp` from the command palette and select `Preferences: LSP Settings`
4. In LSP.sublime-settings, add the following:

```
// Packages/User/LSP.sublime-settings
{
    "clients":
    {
        "anakin":
        {
            "command": ["anakinls"],
            "languageId": "python",
            "scopes": ["source.python"],
            "syntaxes": ["Packages/Python/Python.sublime-syntax"],
            "enabled": true,
            "settings": {
                "anakinls: {"pyflakes_errors": true, "help_on_hover": true},
            },
            "env": {
                // Or some other place where sublime.py and sublime_plugin.py live
                "PYTHONPATH": "/opt/sublime_text/Lib/python33"
            }
        },
    }
}
```
Open a python project with `subl path/to/project`.
Open a python file. Server name "anakin" should be seen in the status bar to the left.
From the command palette run `LSP: Toggle Log Panel`.

**Comment by muffinmad** [comment]
> FWIW You can do the following to test this in ST3:

Yes, I've setup LSP in ST3 in the similar way using LSP documentation. Really helpful ;) With some additional keys:
```
	"log_debug": true,
	"log_payloads": true,
	"log_stderr": true
```

> `"anakinls: {"pyflakes_errors": true, "help_on_hover": true},`

`pyflakes_errors` must be list of class names, e.g. `['UndefinedName', 'UnusedVariable']`
